# Generated by Django 3.0.4 on 2020-03-11 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20200310_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='professor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rate.Professor'),
            preserve_default=False,
        ),
    ]
