# Generated by Django 3.0.4 on 2020-03-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_rating_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')]),
        ),
    ]
