# Generated by Django 3.0.4 on 2020-03-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_auto_20200311_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleinstance',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1 - (Autumn)'), (2, 'Semester 2 - (Spring)')]),
        ),
    ]
